# Jujutsu configuration for R F1 Analytics project

[user]
# Set your name and email (you can override these in ~/.jjconfig.toml)
# name = "Your Name"
# email = "your.email@example.com"

[ui]
# Use vim-style editor for descriptions
# editor = "vim"

# Show diffs with colors
diff-editor = ["vimdiff"]

# Pager for viewing diffs
pager = "less -FRX"

# Default log format
default-command = "log"

[git]
# Push to origin by default
push-remote = "origin"

# Fetch from origin by default  
fetch = "origin"

# Auto-push branches on commit (disable for this project to allow local experimentation)
auto-local-branch = false

[merge-tools]
# Configure diff/merge tools if needed
# vimdiff.program = "vim"
# vimdiff.merge-args = ["-d", "$left", "$right", "$output"]

[aliases]
# Useful aliases for common operations
# Quick status
st = ["status"]

# Log with graph
l = ["log", "-r", "::@", "--no-graph"]
lg = ["log", "-r", "::@"]

# Show changes
d = ["diff"]
ds = ["diff", "--stat"]

# Git interop
gp = ["git", "push"]
gf = ["git", "fetch"]

# Describe current change
c = ["describe"]

# New change on top of current
n = ["new"]

# Squash changes
sq = ["squash"]

[revsets]
# Custom revset aliases
# immutable = "trunk() | tags()"

[templates]
# Custom log template
# log = 'builtin_log_compact'

[colors]
# Enable colors
enabled = true

# Color scheme
"log.change_id" = "yellow"
"log.commit_id" = "blue"
"log.author" = "green"
"log.committer" = "green"
"log.timestamp" = "cyan"
"diff.header" = "yellow bold"
"diff.file_header" = "cyan"
"diff.hunk_header" = "blue"
"diff.added" = "green"
"diff.removed" = "red"
"diff.modified" = "yellow"

[core]
# Automatically track new files (useful for R projects with many scripts)
fsmonitor = true

# Ignore patterns specific to this project (in addition to .gitignore)
# These won't be tracked by jj in local development
excludes = [
    "*.Rhistory",
    ".RData",
    ".Ruserdata",
    "plots/",
    "output/",
    "data/cache/",
    ".f1dataR_cache/",
]
